### ISSUE TITLE
릴리즈 파일 이름 변경이 필요할 것 같습니다

### ISSUE THREAD

**Issue by OctopusET** [hamonikr/nimf#10]
릴리즈 파일의 이름을 1.1.tar.gz 보단 nimf-1.1 등으로 해주시면 더욱 편해질것 같습니다. 최상위 폴더의 이름도 nimf-1.1 이니까요. 감사합니다

**Comment by chaeya** [comment]
@OctopusET 좋은 의견이네요. 다음 릴리즈 시 반영하도록 하겠습니다.
