### ISSUE TITLE
qt4의존성은 qt5로 업그레이드 불가한가요?

### ISSUE THREAD

**Issue by OctopusET** [hamonikr/nimf#11]
qt4가 지원이 끝난걸로 알고 있고 일부 배포판에서는 공식 패키지로 지원 안하는경우도 있더군요 업그레이드 하고 의존성을 없애는 일이 언젠가는 필요할 것 같습니다 감사합니다

**Comment by OctopusET** [comment]
우선 제가 업그레이드 방법을 참고해서 수정해보겠습니다

**Comment by LukeHan1128** [comment]
@OctopusET 좋은 의견인것 같습니다. 공유해 주시면 검토후 반영하도록 하겠습니다.

**Comment by wcho** [comment]
Ubuntu 20.04에서 qt4 지원이 없어져서 혼자 쓰려고 간단히 qt4 의존성만 제거해 보았습니다.
혹시 필요하신 분은 빌드해서 사용하세요.
https://github.com/wcho/nimf/commit/56409a8fb7ad96f8a518dc0e49f0633c4edf96fb

**Comment by OctopusET** [comment]
그냥 qt4만 지우면 되는 거였군요, 커밋하셔도 될것같은데요?

**Comment by wcho** [comment]
@OctopusET 제대로 코드를 정리하지 않고 빌드만 되게 한 거라서 upstream에 머지할 수준은 안되네요. 그리고 qt4를 지원이 필요한 사람도 있을 수 있는데 아예 지원하지 않게 빼는 것도 좀 그렇고요. 타겟 플랫폼 별로 빌드가 되게 하는 게 좋을텐데 어떻게 하는지 모르겠습니다.
