### ISSUE TITLE
만자로 크롬에서는 한영키가 안먹힙니다

### ISSUE THREAD

**Issue by ryunohana** [hamonikr/nimf#12]
안녕하세요 덕분에 만자로에서 nimf 잘 사용중입니다 감사합니다 :)

다른 프로그램은 다 정상적으로 한영키가 작동하는데

크롬 기반 웹브라우저에서는 한영키가 작동을 하질 않네요

이게 저만 그런 문제인지 궁금합니다

**Comment by chaeya** [comment]
만자로에서는 아직 다양한 프로그램에 대한 테스트를 하지 못했습니다.
사용중인 버전과 윈도우매니저를 알려주시면 확인해보도록 하겠습니다. ^^

**Comment by ryunohana** [comment]
네 만자로 18.1.5 Gnome 입니다 :)

**Comment by chaeya** [comment]
테스트한 컴퓨터는 Manjaro-18.0.4 Cinnamon, 크롬은 동일한 버전입니다.
제가 가진 만자로 환경에서는 정상적으로 한글입력이 되고 있습니다.
