### ISSUE TITLE
한글 자동 교정 기능?

### ISSUE THREAD

**Issue by sebuls** [hamonikr/nimf#15]
libhangul 문제인지, ibus-hangul 문제인지 모르겠는데
한글 자동 교정 기능(예를 들어 강 을 치려 했는데 ᄀᅠᆼㅏ이런 식으로 순서를 잘못쳤을 때 자동으로 강으로 바꾸어주는)이 안 되네요.
예전에는 되던 기능인데 언제부턴가 안 되네요.
nimf 에서는 한글 자동 교정 되나요?

**Comment by chaeya** [comment]
현재로서는 사용하기 자동교정, 모아치기는 사용하기 어려울것 같습니다.
@sebuls libhangul 에서 이야기한 아래 이슈를 참고하시면 될것같습니다.
https://github.com/libhangul/ibus-hangul/issues/49
