### ISSUE TITLE
nimf 한글입력 외 건에 대해서

### ISSUE THREAD

**Issue by OctopusET** [hamonikr/nimf#19]
nimf는 한글 입력기만을 위한것이 아니라 ibus같이 여러 문자를 입력할 수 있는 방향으로 개발 되었다고 알 고 있습니다. 지금 nimf 내에서는 anthy rime libhangul m17n 같이 여러 문자입력 패키지가 함께 되있는데, 한번에 설치 하는 방향으로 해야할지 아님 nimf-hangul(ibus 같이) 이런 식으로 세분화 해야 할지 궁금하네요. 님프가 한글입력 사용자외에도 세계의 많은 사용자가 사용했으면 하는 마음에 글 올려봅니다.

**Comment by chaeya** [comment]
한글 입력환경이 아닌 다른 언어 사용자도 모두 사용할 수 있는 입력기가 되는 것이 좋은 방향일것 같습니다.  nimf 에는 중국어 일본어 등 다른 언어를 지원하는 기능도 포함되어 있지만 다른 언어 사용자의 환경에서 이 부분을 검증하고 배포에 필요한 문서를 작성하는것이 필요하겠네요.  언제든 좋은 의견이 있으시면 함께 고민해보시죠.
