### ISSUE TITLE
nimf-libhangul 파일 저장소에 추가

### ISSUE THREAD

**Issue by chaeya** [hamonikr/nimf#2]
https://hamonikr.org/Free_Board/68484

하모니카 님프 저장소를 추가하면 nimf-libhangul 파일을 설치 할 수 없더군요. 이 저장소는 님프 개발자 호동님의 저장소입니다.
 
하모니카 팀에서 확인 추가 해주시면 좋을 거 같네요. 

호동님 저장소는 어떻게 될지 모르니...

**Comment by LukeHan1128** [comment]
nimf-libhangul 패키지를 하모니카 me 저장소에서 제공하도록 구성하였습니다.

apt-get install 명령을 통해 me 저장소에서 제공받아 설치 되는 것 확인했습니다. 

해당 이슈를 close 하도록 하겠습니다.

**Comment by chaeya** [comment]
하모니카 저장소에 의존성이 있는 패키지도 모두 추가

빌드문서는 별도로 작성하여 아래에서 공유 중
https://github.com/hamonikr/nimf/wiki
