### ISSUE TITLE
VsCode Vim plugin의 im-select 설정 문의

### ISSUE THREAD

**Issue by ok97465** [hamonikr/nimf#22]
안녕하세요.

Vim Plugin에서 autoSwitchInputMethod 기능을 사용해보려고 하는데 내용을 찾기가 쉽지 않네요.

https://github.com/daipeihust/im-select#Usage 에는 Linux에서 ibus, fcitx에 대한 설정 방법만 제공 하고 있네요.

읽어주셔서 감사합니다.
좋은 하루 되세요.

**Comment by jerry901** [comment]
settings - extention - Auto Switch Input Method에 스위치 하고자 하는 IM을 입력해주시기 바랍니다.

**Comment by hodong-kim** [comment]
전에도 이 문제를 말씀하신 분이 계셨었는데 이 기능이 왜 필요한지 왜 이 기능을 사용하려 하는지 그 이유부터 알고 싶습니다.

**Comment by xvzc** [comment]
@hodong-kim vim 키맵핑을 사용하는 경우 normal mode에서 hjkl을 방향키로 사용하는데 입력모드가 한글로 설정되어있는 경우 방향키가 제대로 동작하지 않는 이슈입니다. 입력기에 의존적인 이슈라기 보다는 한글을 모국어로 사용하기 때문에 발생하는 고질적인 문제라고 볼 수 있을 것 같습니다.

**Comment by xvzc** [comment]
해당 이슈가 발생하는 경우는 vim Insert mode에서 한글을 입력하다가 Normal mode로 전환한 경우입니다. 

 nimf 입력기에서 ESC 키를 누르면 자동으로 영문 입력모드로 바뀌도록 설정할 수 있는 방법이 있어서 입력기 설정으로 해결할 수 있는 이슈라고 판단됩니다. 

(Insert mode에서 Normal mode로 전환할 때 ESC를 사용하는 유저들에 한해서..)

**Comment by hodong-kim** [comment]
> 해당 이슈가 발생하는 경우는 vim Insert mode에서 한글을 입력하다가 Normal mode로 전환한 경우입니다.
> 
> nimf 입력기에서 ESC 키를 누르면 자동으로 영문 입력모드로 바뀌도록 설정할 수 있는 방법이 있어서 입력기 설정으로 해결할 수 있는 이슈라고 판단됩니다.
> 
> (Insert mode에서 Normal mode로 전환할 때 ESC를 사용하는 유저들에 한해서..)

예, 맞습니다. nimf 입력기에 ESC 를 시스템 키보드로 전환하는 키로 사용할 수 있는 기능이 있습니다.

nimf-settings 를 열고, 좌측 메뉴에서,

언어 엔진 ==> 시스템 키보드 ==> 시스템 키보드로 전환하기 위한 단축키

에서 `Escape`키를 등록하시면 ESC 를 눌렀을 때 영문으로 전환됩니다.

이 기능을 사용하시면 되겠습니다. 감사합니다.
