### ISSUE TITLE
사용 중 nimf instance가 2개가 됨.

### ISSUE THREAD

**Issue by jspark-gigworks** [hamonikr/nimf#29]
### 사용 환경
Ubuntu 20.04를 사용 중이고 2020년 10월 중에 가이드대로 설치했습니다.
ppa가 하모니카 OS 전용이다 보니 제 Ubuntu에 설치되어 있는 파일들이 모두 뒤섞이는 문제가 있어서 설치 이후 Nimf를 update하지는 못한 상황입니다.
`nimf -v` 결과는 `nimf 2019.08.14`로 나오네요.

### 문제점
처음 부팅해서 사용하면 특별히 문제가 없는데, 조금 사용하다 보면 nimf process가 2개가 됩니다.
indicator 영역에도 아이콘이 2개 생기고, ps를 봐도 2개가 되네요.
원인을 찾기 위해서는 어디를 체크해봐야 할까요?

**Comment by chaeya** [comment]
현재 사용중인 하모니카 저장소를 삭제하고 아래 명령으로 저장소를 업데이트 해보시기 바랍니다.
(이 저장소는 Ubuntu 시스템에 사용되는 다른 패키지가 없고 하모니카 팀에서 제공하는 패키지만 있으니 업데이트 하셔도 됩니다.)

```
sudo rm -f /etc/apt/sources.list.d/hamonikr.list

curl -sL https://pkg.hamonikr.org/add-hamonikr.apt | sudo -E bash -

# 현재 설치된 nimf 를 삭제
sudo apt purge nimf nimf-libhangul libnimf1 

# Install nimf from pgk.hamonikr.org
sudo apt install nimf nimf-libhangul

im-config -n nimf
```
시스템을 재 시작한 후 확인해주세요.

**Comment by jspark-gigworks** [comment]
알려주신대로 새 PPA를 등록하여 사용해 봤는데, 아이콘이 2개 나타나는 문제는 아직까지 발생하지 않았습니다만,
대략 해당 증상이 나타날 시점 쯤 되었을 때 아래와 같은 내용의 Ubuntu 오류창이 뜨네요.

![Nimf-error](https://user-images.githubusercontent.com/72600846/98517192-dea6e480-22b0-11eb-8630-9be14a4fd509.png)

상세 내용을 올려 보려 했지만, 내용이 매우 길고 copy & paste가 안되네요.

Stack trace만 캡쳐해서 올립니다.
![Nimf-error-stacktrace](https://user-images.githubusercontent.com/72600846/98517568-7278b080-22b1-11eb-8c62-0e33e113023a.png)

**Comment by jspark-gigworks** [comment]
하루 켜 놓고 났더니 2개 뜨는 증상이 발생했네요.

![double-nimf](https://user-images.githubusercontent.com/72600846/98631413-ba0a4580-2360-11eb-9c61-f794e3befeaa.png)

**Comment by chaeya** [comment]
@jspark-gigworks 화면에 보이는 내용으로는 nimf 아이콘이 하나로 보입니다.  "한" 이라고 표시된 아이콘은 어떤 프로그램에서 나오는 건가요?

**Comment by jspark-gigworks** [comment]
"한"도 Nimf icon입니다.
입력이 가능한 곳에 포커스가 가면 "한", 영문일 때 키보드 모양의 아이콘이 나오고,
입력이 불가능한 곳에 있으면 요정(나비?) 아이콘으로 바뀝니다.
위의 스크린샷의 경우 왼쪽의 아이콘은 그냥 떠 있는 것이고요, 뒤에 있는 "한" 아이콘이 실질적으로 동작하는 것으로 보시면 됩니다.

그리고, 덧붙여서, 아이콘이 2개 있던 상황에서 자리를 비워 화면이 잠겼다가 풀고 났더니 오류가 다시 발생했었고, 그래서 지금은 1개만 떠 있는 상황입니다.

**Comment by chaeya** [comment]
커뮤니티에 남긴글을 보면 이전에 nimf 설치시 저장소가 여러개 겹처서 문제였던것이라고 한것 같습니다. 해결된 것으로 알고 이슈를 닫습니다.

**Comment by jspark-gigworks** [comment]
이것도 위의 다른 이슈처럼 저장소 문제 해결 후에도 동일하고 발생하는 문제입니다. Reopen 부탁드려요.

**Comment by chaeya** [comment]
제가 테스트한 환경에서는 오류가 재현되지 않습니다.
새버전의 패키지가 업데이트 되었으니 이전에 사용하던 nimf 를 모두 삭제하시고 한번 해보세요.

**Comment by eubnara** [comment]
```
sudo apt remove nimf nimf-libhangul libnimf1
sudo apt purge nimf nimf-libhangul libnimf1
sudo apt install nimf nimf-libhangul
im-config -n nimf
```

위 명령으로 저도 재설치를 진행하고 재시작했는데도 동일한 현상이 발생하네요. nimf 프로세스는 하나만 떠있는 듯 한데 이상합니다.

```
❯ ps -ef | grep nimf
eub         1782    1690  0 11:02 ?        00:00:00 nimf
eub         5630    3230  0 11:10 pts/1    00:00:00 grep --color=auto nimf
```

아이콘 그림이 미묘하게 화질이 다른 것 같긴한데...


![image](https://user-images.githubusercontent.com/12639125/233756320-8982b17b-26ff-414b-82c4-0e905f45e5a8.png)
![image](https://user-images.githubusercontent.com/12639125/233756346-834cd63f-f806-4621-a8d7-a4fdda359dfe.png)
![image](https://user-images.githubusercontent.com/12639125/233756356-3ec13c4f-a0c3-4e02-8a36-ad52d5d86340.png)
