### ISSUE TITLE
not working in applications, only in terminal

### ISSUE THREAD

**Issue by mxa** [hamonikr/nimf#31]
I've got nimf input installed in Kubuntu 20.10 with the groovy repository, but I can't enable the korean input in apps like LibreOffice, Inkscape, Firefox. The only place where it works for me is the Terminal (and that's not very useful). Any ideas what could cause that issue?

**Comment by chaeya** [comment]
@mxa I installed kubuntu 20.10 today. and tried install nimf.
But i coudn't found problem as you said.

So i upload video. Could you check blow link?
https://youtu.be/3j12kAwgols

**Comment by cheuksing** [comment]
Probably env is not set. Did you set gtk im module and other variable in .xinitrc or .profile @mxa

**Comment by mxa** [comment]
Just in time my solid state memory with the system completely failed, so I set up a fresh install and it works there. Must have been something on that old system which was upgraded many times.
