### ISSUE TITLE
저작권 침해를 중단하시기 바랍니다.

### ISSUE THREAD

**Issue by nimfsoft** [hamonikr/nimf#33]
안녕하세요.
님프 저작권자 김호동입니다.
최근 하모니카 nimf 를 확인해보니,
저작권자인 저를 삭제하시고 하모니카가 저작권자라고 수정하셨던데

### 저작권 침해를 중단하시고, 저작권자를 원상 복구하시기 바랍니다.

![copyright](https://user-images.githubusercontent.com/75158510/101234252-fed79100-3700-11eb-966d-34cd9c297c8d.png)

### 저자 목록에서 하모니카를 삭제하시기 바랍니다.

또한, 님프 저자에 하모니카를 추가하셨던데
단순히 문서를 변경하거나 그림 파일만 변경한 걸로는 저자로 등재하기 어렵습니다.

### 저작권 침해에 대한 재발 방지 약속 바랍니다.

전에 소스코드 변경이 없던 상태에서 저작권자와 협의없이 라이선스를 LGPL 에서 GPL 로 일방적으로 변경하는 일도 있었습니다.
이번에는 저작권자인 제 이름을 삭제하시고 하모니카 이름을 넣으셨는데 재발 방지를 약속하시기 바랍니다.

**Comment by nimfsoft** [comment]
스크린샷을 잘못 넣어서 내용을 일부 수정했습니다.

**Comment by nimfsoft** [comment]
https://github.com/hamonikr/nimf/blob/42d26c3cbc2bc318b7bc22058906cf409a4fa054/AUTHORS

```
HamoniKR Developement Team <root@hamonikr.org>
Kevin Kim <chaeya@gmail.com>
```

단순히 그림 파일, 문서 파일을 수정한 걸로는 저자 목록에 등재하기 곤란합니다.
저자 목록에서 삭제되어야 합니다.

https://github.com/hamonikr/nimf/blob/960916a36c4c459704d73fc8cb94143330eb3115/po/ko.po
https://github.com/hamonikr/nimf/blob/ee458fff6e1702b7e26f4f8caa718e15eff3ffc0/po/ko.po

```
#: ../modules/services/indicator/nimf-indicator.c:122
msgid "Copyright (c) 2019-2020 HamoniKR Community"
msgstr "저작권 (c) 2019-2020 하모니카 커뮤니티"

#: ../modules/services/indicator/nimf-indicator.c:122
msgid "Copyright (c) 2019-2020 HamoniKR"
msgstr "Copyright (c) 2019-2020 하모니카"
```

https://github.com/hamonikr/nimf/blob/42d26c3cbc2bc318b7bc22058906cf409a4fa054/modules/services/indicator/nimf-indicator.c

```
      "copyright",          _("Copyright (c) 2019-2020 HamoniKR"),
```

저작권자를 원상 복구하시기 바랍니다.

**Comment by nimfsoft** [comment]
그리고,

아래 `nimf-info.png` 라는 그림 파일이 저작권을 침해하고 있으니 삭제하시기 바라며,
https://github.com/hamonikr/nimf/blob/ee458fff6e1702b7e26f4f8caa718e15eff3ffc0/docs/nimf-info.png

배포 중인 바이너리 파일 `nimf_1.3.0hamonikr40.3_amd64.deb` 저작권을 침해하고 있으니 삭제하시기 바랍니다.
https://github.com/hamonikr/nimf/releases/download/1.3.0/nimf_1.3.0hamonikr40.3_amd64.deb

```
strings libnimf-indicator.so | grep HamoniKR
Copyright (c) 2019-2020 HamoniKR
```

**Comment by nimfsoft** [comment]
저작권 침해 부분을 또 발견하였습니다.
하모니카가 님프를 만들지 않았으며, 하모니카는 님프 저자가 아닙니다. 따라서, 다음을 삭제하시기 바랍니다.

https://github.com/hamonikr/nimf/blob/ee458fff6e1702b7e26f4f8caa718e15eff3ffc0/modules/services/indicator/nimf-indicator.c#L110

```
    gchar *authors[]     = {_("HamoniKR <pkg@hamonikr.org>"),
```

하모니카 측에서 저작권자를 김호동에서 하모니카로 바꿔치기하고 저자에 하모니카를 넣으니 님프를 하모니카가 만들었다는 효과가 나타납니다. 이해하기 쉽게 그림을 첨부하니 보시기 바랍니다.

![copyright-infringement1-1](https://user-images.githubusercontent.com/75158510/101273321-7d9efd80-37d7-11eb-9846-795b9e00270f.png)
![copyright-infringement2-2](https://user-images.githubusercontent.com/75158510/101273324-81cb1b00-37d7-11eb-9fc1-9a94b57367b2.png)

거듭 요청 드립니다. 저작권 침해를 중단하시기 바랍니다.

**Comment by nimfsoft** [comment]
하모니카 측은, 원저자의 코드를 거의 그대로 유지한 상태에서, 최종사용자가 소프트웨어를 사용하면서 보게 되는 About 다이얼로그에 나오는 원저작권자를 삭제하고 저작권자를 하모니카로 교체하는 것이 올바른 행위인지 생각해보시기 바랍니다.
제가 지금은 리눅스를 사용하지 않습니다만, 수년간 어이없는 일들 많이 봐왔고, 더 이상 이런 문제에 대해 신경쓰고 싶지 않습니다.
이것은 저작권 포기를 의미하는 것이 아니며 저작권 양도를 의미하는 것이 아닙니다.
또한 앞으로 이의 제기를 하지 않겠다는 의미도 아닙니다.
이번 일을 계기로 모두 자성의  시간을 갖으시기 바랍니다.
이슈를 닫겠습니다.

**Comment by chaeya** [comment]
저작권 침해라고 판단하셨다니, 우선 미흡한 조치에 사과드리며, 사실에 근거하여 답변드리겠습니다.

1) 원저작자를 삭제한게 아니라 HamoniKR 개발팀을 저작권자에 추가하였습니다.

2) 저자로 표시된 사람에게 연락이 되지 않는 다는 이슈가 있었습니다. 참고해주세요.
https://github.com/hamonikr/nimf/issues/23

3) 또한 하모니카 팀이 현재 이 프로젝트의 저자로 지속적인 이슈처리와 소스코드 수정, 문서화 등을 진행하고 있으므로 저자로 표현해도 될 것으로 판단했습니다.
처리된 이슈 : https://github.com/hamonikr/nimf/issues?q=is%3Aissue+is%3Aclosed
업스트림 프로젝트에서 변경내역 : https://github.com/hamonikr/nimf/compare/dec1a11c3034677a825b0dff319a05a8d019ae08...chaeya:master

저작권 침해라고 표현하신 부분에 대하여 설명을 드렸지만
하모니카 개발팀은 원저작자인 김호동님의 의견이 가장 우선되어야 한다고 생각하며, 
요청하신 내용을 반영하도록 하겠습니다.

좋은 소프트웨어를 오픈소스로 공개해주신 원저작자 김호동님에게 감사하고 있습니다.
이 프로젝트를 누구보다 잘 아시는 분이니, 가능하다면 지속적인 님프 프로젝트 참여를 환영합니다.

**Comment by nimfsoft** [comment]
빠른 답변 감사드립니다.

> 원저작자를 삭제한게 아니라 HamoniKR 개발팀을 저작권자에 추가하였습니다.

최종 사용자분이 접하게 되는 About 창에 저작권자인 제 이름이 삭제되고 HamoniKR 가 들어간게 맞습니다. 스크린샷 그림을 보면 알 수 있습니다. 제가 가장 크게 문제 삼는 부분이 바로 그 부분입니다.

```
Copyright (c) 2019-2020 HamoniKR
```

그 다음으로 문제 삼는 부분이... About  창에 Credits 탭에서

```
Created by HamoniKR
           Hodong Kim
```

이 부분 입니다. 소프트웨어 사용자 대부분은 README 이런거 안 봅니다. 처음 사용자 입장에서 그 두가지(Copyright, Created by)를 보면 Nimf 를 하모니카가 2019년에 개발했고 Nimf 의 원저자 및 저작권자가 하모니카라고 인식할 것입니다.

예를 들어, ibus 소스코드를 그대로 가져온 상태에서 README 파일을 수정하고, 사용자가 접하게 되는 About 관련 소스코드에서 About 메뉴에 나오는 Copyright 년도 저작권자 이름을 삭제하고, Copyright 2020 홍길동 이렇게 교체한 후 패키지를 만들어서 배포해도 아무 문제가 없을까요?

LGPL 오픈소스이고, 소스코드의 저작권, 라이선스 헤더를 유지하고 있습니다만, 최종 사용자가 접하게 되는 About 창의 저작권자 부분에서 원래 있던 저작권자를 삭제하고 하모니카를 넣어도 라이선스상, 저작권법상 문제가 없는 것인지 제가 법률가가 아니라 그것까지는 잘 모르겠습니다.

또한 원저자의 코드를 거의 그대로 유지한 상태이고, 소프트웨어 바이너리 또는 패키지에 영향이 가지 않는 파일들을 수정하거나 추가한 경우 `AUTHORS` 파일에 저자로 등재하는 것이 바람직하지 않다고 보는 입장입니다.
소스코드 중에 `gchar *authors[]     = { ... };` 저자 관련 부분이 있는데, 이 부분은... 최종 사용자 분이 접하는 About 창에

```
Created by ...
```

이렇게 표현되는 부분입니다. 그리고 어떤 소프트웨어의 경우 저자가 저작권자가 아닌 경우도 있습니다. Nimf 의 경우는 제가 저작권을 양도한 적이 없기 때문에 저자와 저작권자가 같은 거고요.

일반적으로, 하모니카측에서는 하모니카가 작성한 것에 대해서 저작권을 보유합니다. Nimf 에도 여러 기여자분들이 계신데 기여자분들이 작성하신 부분은 기여자분들이 저작권을 보유합니다. 그런데 애매한 부분이 있어서 항상 그런 것도 아닙니다.
하모니카 측에서 로고 파일을 제작하고, 아이콘 파일을 제작하여 추가 또는 교체하시는 등의 노력도 기울였고, 그 부분에 대해 저작권을 보유한다고 할 수 있는데, About 창에서 저작권자에 하모니카가 안 나오면 하모니카 입장에서는 좀 허망하다는 느낌도 들 수 있겠습니다. 그리고 여러 기여자분들이 계시는데 그분들은 나름 자기가 할 수 있는 범위 내에서 많은 시간을 공들인건데 그분들도 허망하다는 느낌이 들 수도 있겠습니다. 제가 그걸 모르는 바 아닙니다.

`gchar *authors[]` 에는 HamoniKR 를 추가하였지만, `"copyright"` 에는 제 이름을 삭제하고 HamoniKR 로 교체하셨던데... 그러면서 연도는 2015년부터가 아니고.. 의아하게 생각했습니만, 하모니카측에서 원상 복구하신 걸 보니, 저작권 침해 의도는 없어 보입니다.
저자 넣는 부분은 `gchar *authors[]` 문자열 배열이라 제 이름을 보존하면서 HamoniKR 를 추가하시고
저작권자 넣는 부분은 `gchar *` 문자열이어서 두 명 넣기가 곤란해서 교체를 하신거 아닌가... 그런 생각이 드는군요.

About 창에

```
Copyright (c) 2015-2020 Hodong Kim
Copyright (c) 2020 HamoniKR
```

이렇게 표시되는게 좋겠습니다.
Copyright (c) 2015-2020 Hodong Kim 여기서 왜 2020년이냐면 제가 2020년에 작성한 `nimf-2020.04.28.patch` 패치가 적용되었기 때문입니다.
Copyright (c) 2020 HamoniKR 여기서는 왜 2020년이냐면 하모니카측에서 제작한 로고 그림 파일, 아이콘 파일이 2020년에 추가되었고 그것이 소프트웨어에 실제로 사용되기 때문입니다.

시간날 때 About 창에 관련한 패치를 작성하여 PR 올리도록 하겠습니다.
저는 이 문제가 원만히 해결되기를 바랍니다.
감사합니다.

**Comment by chaeya** [comment]
@nimfsoft 하모니카 개발팀은 원작자 김호동님의 기여를 가장 중요하게 생각합니다. 따라서 언제든 프로젝트에 수정요청이 있으시면 최우선으로 반영하겠습니다. 그리고 바쁘시겠지만 프로젝트 원작자분이 관심있게 지켜봐주시면 많은 사람들이 좋은 소프트웨어를 사용할 수 있을것이라고 생각합니다. 종종 들러서 문제점을 말해주시고 리뷰 부탁드립니다. 즐거운 하루 보내세요~

**Comment by chaeya** [comment]
@nimfsoft Maintainer 권한의 프로젝트 멤버로 초대했습니다. 오랜 기간 오픈소스 프로젝트 하시면서 여러가지 일들 때문에 마음이 상하셨겠지만, 좋은 오픈소스를 공개하셔서 nimf는 많은 분들이 애용하고 있으니 원작자로서 가끔씩 시간나실때 보시고 여러가지 의견 주세요~
