### ISSUE TITLE
https://kldp.org/node/161791

### ISSUE THREAD

**Issue by opqriu** [hamonikr/nimf#40]
https://kldp.org/node/161791

여기 마지막 댓글로 어떤 분이 익명으로 11월 말일에 GtkEntry Patch 건의를 해주셨는데 적용해 주시믄 좋을것같아요.

**Comment by chaeya** [comment]
@opqriu 알려주신 링크는 nimf 가 아니라 gtk를 수정하는 내용으로 보입니다.
