### ISSUE TITLE
리브레오피스 자동고침 관련

### ISSUE THREAD

**Issue by queenmedley** [hamonikr/nimf#41]
리눅스에서 리브레오피스 사용하면서 끝글자 사라지는 문제는 오늘 nimf 를 설치하면서 겨우 해결이 되어 기쁘네요.
근데 리브레오피스 라이터에서 자동고침이라는 기능이 있는데 거기에서 글자를 입력하고 스페이스바를 누르면 자동으로 고쳐져야되는데
한글은 역시나 입력기마다 문제가 다양하게 있네요..
ibus는 한글을 입력하고 나서 오른쪽 방향키를 한번 눌러주고 스페이스바를 누르면 변환이 되고
nimf는 한글을 입력하고 나서 엔터키를 누르거나 방향키로 오른쪽으로 갔다가 다시 단어 끝으로 되돌아와서 스페이스바를 눌러야 변환이 됩니다.

한글입력기와 리브레오피스 어느쪽에서 고쳐져야하는 문제인지 컴맴인 저로서는 알수가 없는지라 여기 글을 남겨봅니다.
리브레오피스에도 신고를 하도록하겠습니다.

**Comment by hodong-kim** [comment]
확인해보지는 않았지만 그게 아마 리브레오피스 버그일 것입니다.
