### ISSUE TITLE
Unable to input Hangul in Zoom/님프를 사용하여 줌 채팅창에 한글 입력불가

### ISSUE THREAD

**Issue by Redpillbug** [hamonikr/nimf#43]
**버그 설명**
영상 회의 프로그램 줌에 님프/Nimf를 사용한 한글 입력이 되지 않음.

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. 데미안용 [줌](https://us04web.zoom.us/support/down4j)을 설치
2. 계정에 로그인
3. 줌의 오른쪽 상단 "새로운 미팅" 버튼(주황) 클릭
4. "chat" 버튼을 눌러 채팅창을 열고, 오른쪽 alt 또는 한/영 키를 눌러 한글 입력를 시도

**예상한 결과**
줌 채팅창에 한글이 입력되어야 함.

**자신의 PC 환경**
 - OS:  LMDE (리눅스 민트 데비안 애디션)

**Comment by makerdark98** [comment]
* Many program based on Qt receives inputs using Qt Virtual Keyboard. Zoom is also based on Qt.
* They use inputplugin library in `platforminputcontexts`. But many of them does not consists of nimf's library.
* If you want to use nimf in zoom, input this file(`libqt5im-inf.so`).

Qt 기반 프로그램들은 가상 키보드라는 개념을 사용해서 입력을 받는데, 이게 잘 동작하지 않는 것으로 보입니다.
라이브러리 파일을 줌이 설치된 위치에 넣어주시면 동작할 것 같아보입니다. (전역으로 이 라이브러를 설치하는 방법은 저도 몰라서...)
구체적인 방법을 명령어기반으로 아래에 첨부하겠습니다.

1. Find `libqt5im-nimf.so`
 * Default `libqt5im-nimf.so` location : `/usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/`
 
2. Find zoom location
```
ls -l $(which zoom) # /opt/zoom/ZoomLauncher
```

3. Copy library file
```
cp libqt5im-nimf.so /opt/zoom/platforminputcontexts # It can be required sudo.
```

참고 자료 : https://www.nemonein.xyz/2018/11/1264/

**Comment by whale124** [comment]
오!! 해결하였습니다. 감사합니다.

**Comment by junghan0611** [comment]
감사합니다. !

**Comment by ChanJoon** [comment]
Zoom 내 `platforminputcontexts` 경로가 바뀌어, 혹시 찾으시는 분들을 위해 남겨둡니다.

```bash
sudo cp /usr/lib/x86_64-linux-gnu/qt5/plugins/platforminputcontexts/libqt5im-nimf.so \
  /opt/zoom/Qt/plugins/platforminputcontexts/
sudo chmod 644 /opt/zoom/Qt/plugins/platforminputcontexts/libqt5im-nimf.so
```

위와 같이 하시고 Zoom 켜시면 한글 사용 가능해집니다.

**Comment by mxa** [comment]
How to remove the bogus ibus dependancy of Zoom:
https://hashman.ca/zoom/
