### ISSUE TITLE
한글 레이아웃 조그만 변경이 가능한지에 대해서

### ISSUE THREAD

**Issue by rayshoo** [hamonikr/nimf#44]
아주 개인적인 이유로 '영어'가 아닌 '한글' 자판일 경우에만 키를 두개 바꾸고 싶은데
fork해서 이 부분만을 수정해서 쓰고 싶어도 부끄럽지만 부족한 실력으로 방법을 전혀 모르겠어서..ㅜ
혹여 방법을 아시는분이 계실까하여 질문 남겨놓습니다 감사합니다

### 두벌식 한글 변경하고 싶은 부분
<kbd>;</kbd> : <kbd>ㅔ</kbd><br>
<kbd>ㅔ</kbd> : <kbd>;</kbd><br>

**Comment by hodong-kim** [comment]
nimf는 libhangul 을 사용하고 있으니 libhangul 에 그러한 기능이 있는지 알아보시거나 만약 없다면 libhangul 을 수정하여 사용해야할 것 같습니다.
