### ISSUE TITLE
구형 미니 랩탑에 데비안 깔았는데 님프 설치가 안 돼요.

### ISSUE THREAD

**Issue by opqriu** [hamonikr/nimf#45]
안녕하세요?
조그만 미니 노트북에 debian 10 mate를 깔았습니다.
readme에 나와있는대로 입력했구요.

curl -sL https://apt.hamonikr.org/setup_hamonikr.sun | sudo -E bash -

  하모니카 (SUN) 저장소 설정 완료

  하모니카 OS의 저장소를 추가하고 설치가능한 패키지 목록을 업데이트 했습니다.
  이제 하모니카 팀에서 제공하는 패키지를 설치할 수 있습니다.

sudo apt install nimf nimf-libhangul

패키지 목록을 읽는 중입니다... 완료
의존성 트리를 만드는 중입니다       
상태 정보를 읽는 중입니다... 완료
E: nimf 패키지를 찾을 수 없습니다
E: nimf-libhangul 패키지를 찾을 수 없습니다

이렇게 나오네요.
도움을 주시면 감사하겠습니다.

**Comment by MoorDev** [comment]
sudo apt update
이 명령을 한 이후에도 안 되나요

**Comment by opqriu** [comment]
> sudo apt update
> 이 명령을 한 이후에도 안 되나요

자문자답 합니다.
구형 랩탑이라서 32비트 데비안을 깔았는데
이게 문제인거 같네요.
생각도 못했습니다 ㅎㅎ
