### ISSUE TITLE
Install error ... on Manjaro 20.2

### ISSUE THREAD

**Issue by egido03** [hamonikr/nimf#46]
**버그 설명**
install error(?)... from [Install from PKG]

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
[of1@of1-b450m 다운로드]$ sudo pacman -U ./nimf-2019.08.14-1-any.pkg.tar.xz

[sudo] of1의 암호: 
꾸러미 불러오는 중...
의존성 해결 중...
경고: "nimf"의 의존성 "qt4"를 해결할 수 없습니다.
:: 해결할 수 없는 의존성 때문에 다음 꾸러미를 업그레이드 할 수 없습니다:
      nimf

:: 이 업그레이드에 대해 위 꾸러미를 건너뛰시겠습니까? [y/N] y
꾸러미 충돌을 찾는 중...
 할 일이 없습니다

---------------------------------------------------------------------------------------------------------------
[of1@of1-b450m 다운로드]$ sudo pacman -U ./nimf-2019.08.14-1-any.pkg.tar.xz
꾸러미 불러오는 중...
의존성 해결 중...
경고: "nimf"의 의존성 "qt4"를 해결할 수 없습니다.
:: 해결할 수 없는 의존성 때문에 다음 꾸러미를 업그레이드 할 수 없습니다:
      nimf

:: 이 업그레이드에 대해 위 꾸러미를 건너뛰시겠습니까? [y/N] n
오류: 트랜잭션 준비에 실패했습니다(의존성이 만족되지 못하였습니다.)
:: 의존성 'qt4'(nimf가 요구)를 만족시킬 수 없습니다
[of1@of1-b450m 다운로드]$

**예상한 결과**
install completed...
my two daughter use manjaro and nimf but my computer can't install nimf...

**Screenshots**
가능하다면 화면 캡처를 포함해주세요. (이미지를 드래그앤드롭으로 업로드하세요)

**자신의 PC 환경**
 - OS: I'm on Manjaro 20.2  my daughter is on manjaro 18.xx
 -       KDE Plasma 5.21.3
 - Browser []
 - Version []

**Comment by egido03** [comment]
안녕하세요.
쌍둥이 아빠입니다.  만자로에서 설치가 안되어서 콩글리시로 내용 올렸네요.

계속 QT4 관련 설치 에러가 발생해서 사용을 못하고 있습니다.
어떻게든 도움을 받고 싶어서 여기 올렸습니다.

**Comment by hellojaccc** [comment]
`git clone https://github.com/hamonikr/nimf`

`cd nimf/archlinux`

`makepkg` 해서 나온 .tar.xz 파일을 `pacman -U` 로 설치하시면 됩니다.

**Comment by hellojaccc** [comment]
`nimf` AUR 패키지를 설치하시는 것도 가능합니다.
