### ISSUE TITLE
Kali 리눅스에서 libappindicator 의존성 관련 이슈

### ISSUE THREAD

**Issue by 7k5x** [hamonikr/nimf#47]
칼리 리눅스에서 nimf를 설치하려고 하면 libappindicator가 저장소에 없다는 오류가 나옵니다.
이건 칼리 리눅스 저장소의 문제이기도 하지만, 리드미에 있는 스크립트(https://pkg.hamonikr.org/add-hamonikr.apt, https://apt.hamonikr.org/setup_hamonikr.sun)에서 미리 libappindicator를 설치하는 라인을 넣는 것도 좋을 것 같습니다.

**Comment by chaeya** [comment]
공유해주신 문제는 nimf 저장소에 libappindicator 패키지를 추가하고
Kali linux 2021.2 환경에서 정상적으로 설치되는 것을 확인했습니다.

감사합니다.
