### ISSUE TITLE
텔레그램에서 한글 입력이 되지 않음

### ISSUE THREAD

**Issue by partrita** [hamonikr/nimf#49]
**버그 설명**

텔레그램 앱에서 한글 입력이 되지 않음

**버그 재현 과정**

```bash
sudo snap install telegram-desktop
```
을 통해 설치한 앱에서는 한글 입력이 되지 않음

ibus에서도 입력이 되지 않는 문제가 있으나 `fcitx`을 사용하면 해결이 되었음.
https://franzpark.github.io/dev/ubuntu-telegram-korean/

**해결책**

아마도 telegram-desktop에서 수정해야 가능할 듯

**자신의 PC 환경**
 - OS: Ubuntu 20.04

**Comment by chaeya** [comment]
현재 snap 버전의 텔레그램은 nimf 로 한글입력이 되지 않습니다.
텔레그램 deb 파일을 설치해서 사용하시면 정상적으로 입력됩니다.
