### ISSUE TITLE
설치 문의

### ISSUE THREAD

**Issue by ghost** [hamonikr/nimf#5]
https://nimf-i18n.gitlab.io/ko/installation/
에 나와 있는대로 데비안 10 버스터 XFCE에서 설치 시도를 하였습니다.

~$ sudo echo "deb http://ppa.launchpad.net/hodong/nimf/ubuntu bionic main" > /etc/apt/sources.list
첫줄에 나와 있는대로 위 명령을 입력하였더니 아래처럼 허가거부가 뜹니다.
bash: /etc/apt/sources.list: 허가 거부

하모니카로 포크 된 저장소를 통해 데비안 버스터에 설치를 하려면 어떻게 해야 하나요?

**Comment by Scorbie** [comment]
하모니카 관계자는 아닙니다만, 다음과 같은 해결법이 있을 것 같습니다. 다만 sudo를 쓰는 명령이고 직접 테스트해본 것이 아니라 결과에 대해서 아쉽게도 직접 책임져드리지 못한다는 점 이해해주십시오. 조심스럽게 알아보시고 사용해보셔야 할 것 같습니다.

1) 원 소스 이용
이틀 사이에 바뀐 건지는 모르겠지만 설치 페이지에 다음과 같이 나와 있습니다.
```sh
sudo echo "deb http://ppa.launchpad.net/hodong/nimf/ubuntu bionic main" > /etc/apt/sources.list.d/nimf.list
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys C290E34891F9381B
sudo apt update
```
혹시 첫 줄이 같은 오류로 안 된다면 다음과 같은 방법을 사용할 수 있을 것으로 보입니다.
```sh
sudo echo "deb http://ppa.launchpad.net/hodong/nimf/ubuntu bionic main" | sudo tee /etc/apt/sources.list.d/nimf.list
```

2) 하모니카 저장소 이용
https://github.com/hamonikr/nimf#1-apt-저장소-추가
를 참고하면 될 것 같습니다.

혹시 오류가 있을 경우 수정하도록 하겠습다. 감사합니다.

**Comment by mozirani** [comment]
수정해서 알려주신 sudo tee를 활용한 명령어를 쓰니까 정상적으로 되네요.
이제 데비안에서 님프를 설치했고, 끝글자 버그 없이 작성이 잘 됩니다~ ^^
좋으네요.
알려주셔서 감사합니다~~~

**Comment by chaeya** [comment]
@Scorbie 좋은 답변 감사합니다.
