### ISSUE TITLE
tray 아이콘 변경

### ISSUE THREAD

**Issue by hellojaccc** [hamonikr/nimf#50]
![Screenshot_20211005_181444](https://user-images.githubusercontent.com/71537512/135995474-6c53bd36-c39f-487c-b820-42391727755d.png)
시스템 트레이의 아이콘이 하얀색이어서 밝은 테마를 쓸 때 제대로 보이지 않습니다. 기존의 회색 아이콘으로 변경할 수 있으면 좋겠습니다. 

추가로, 대기 상태에서의 나비 아이콘이 거슬리는데 이것도 기존의 회색 아이콘으로 변경할 수 있으면 좋을 것 같습니다.

**Comment by hellojaccc** [comment]
대기 상태 나비 아이콘:
![Screenshot_20211005_181843](https://user-images.githubusercontent.com/71537512/135995973-0226dd04-954e-4de3-80a6-936b2deb81de.png)

**Comment by bdh1993** [comment]
![01](https://user-images.githubusercontent.com/58254473/146307722-dfbe2200-b6ed-4f8e-a540-f5bc103ed2a4.png)
![02](https://user-images.githubusercontent.com/58254473/146307731-533afa48-f346-40e3-9f7d-1f55cc3f3892.png)

흰색 배경화면 상태에서도 보일수 있도록 배경색을 조금 진하게 수정하였고
"한" 이라는 글씨의 배경색이 투명인 상태였는데 검은색으로 변경하였습니다.
