### ISSUE TITLE
Doesn't work on Ungoogled-Chromium Pop!_OS.

### ISSUE THREAD

**Issue by coughingmouse** [hamonikr/nimf#52]
**버그 설명**
It just doesn't work on Pop!_OS, and I have no clue what to do. How do I even go back to ibus the way it actually worked?

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. Install, log out, and log back in
2. It doesn't work
3. Run nimf
4. Invalid layout links are added to the list of Input Sources, but it still doesn't wok
5. Suffer in agony
6. Open Nimf Settings
7. Enable "Setup environment variables, log out, and log back in
8. It seems to work but for my browser and Chinese
9. Deactivate and reactivate rime engine to enable Chinese output
10. still no luck on the browser tho

**예상한 결과**
I should be able to type everywhere, especially on some Chromium browser???

**자신의 PC 환경**
 - OS: Pop!_OS 21.10
- Browser: Ungoogled-Chromium

**Comment by coughingmouse** [comment]
Maybe I should open a new issue for this, but on my setup, typing in Gnome Files to start searching did not function as expected.
Using rime, the symbol of the first keystroke was invalidated, while with libhangul and anthy, the letters were written but was plainly written (e.g. ㄴㅣㅁ프、nインプ), and dragging a character being edited not only moved it around but also selected area from the character's spot to the drag point.

**Comment by bdh1993** [comment]
Hi, Thank you for your comment.

Pop!_OS 21.10 has a code that **forces "IBUS" environment variables**.
You can find **"pop-default-settings"** package. (/etc/profile.d/pop-im-ibus.sh)

There are two solutions.
nimf must be installed & **"im-config -n nimf"** setting.

First, Remove file or comment out content. (/etc/profile.d/pop-im-ibus.sh)

and just reboot  :smile: 

Second, Add the nimf environment variable.
It is similar to the POP_OS 21.10.

**GTK_IM_MODULE=nimf
QT_IM_MODULE=nimf
XMODIFIERS=@im=nimf**

You can write the .bashrc, .profile, /etc/profile ... etc.
or recycle the /etc/profile.d/pop-im-ibus.sh.

and just reboot  :smile:

**Comment by coughingmouse** [comment]
It's not that nimf's not functioning on every application; just on the version of Chromium I'm using, afaict. 
I tested a few apps I use regularly just now to see if it works on them. 
What it works on:
Firefox, Zotero, Gnome apps (Files, Terminal, & Settings were checked), VSCode, Alacritty
Where it doesn't: 
Gnome shell, Discord (flatpak), Ungoogled-Chromium (flatpak), Joplin (flatpak), Bitwarden client (flatpak)

...Now that I list them, I can see that it's probably just with flatpak that nimf doesn't work.
