### ISSUE TITLE
Using Generalized Lock key (Caps Lock) after setting as the hotkey for rotating input method engines still locks layer

### ISSUE THREAD

**Issue by coughingmouse** [hamonikr/nimf#53]
**버그 설명**
When you set the Generalized Lock key as a hotkey (to make it behave like it would on macOS), it should not work as what it used to be. But it does.
This is probably a different bug, but just saying: using xkb hyper (by using xkb option on Caps Lock) as a hotkey is also not possible. It raises "Please report a bug. (keyval:65517)" when pressing the hyper key on the "Press key combination" pop-up menu.

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. Set Caps_Lock or <Lock> Caps_Lock as one of the Nimf Hotkeys and confirm its function
2. Type with a layout with more than two layers to see that the lock key still functions as before.

**예상한 결과**
Generalized Lock key should not lock while used as a hotkey.

**Comment by hodong-kim** [comment]
Caps Lock 키는 다른 키와고는 다르게 좀 특별하게 작동합니다. Num 키도 마찬가지입니다. 이들 키는 그 고유의 기능이 있는데 이를 입력기 언어 전환으로 사용하는 것은 부적절해보입니다. Nimf 에서 Caps Lock 및 Num 키를 언어 전환용으로 선택할 수 없는 것은 버그가 아닙니다.

**Comment by hodong-kim** [comment]
Caps Lock 키 및 Num Lock 를 눌르면 LED가 켜지는 것을 보실수 있을거에요. 그 키들은 토글 기능을 하는데 그 키들은 고유의 기능이 있습니다. 리눅스 또는 BSD 운영체제의 키보드 드라이버에서 그러한 기능이 이미 있는 것이고 그 기능을 응용 어플 차원에서 변경할 방법이 없습니다. 그걸 가능하게 하려면 커널용으로 별도의 키보드 드라이버를 제작해야 하는데 그것은 입력기 범위를 넘어서는 것이고 아쉽더라도 Alt 키나 Super 키, Meta 키 등을 언어 전환용 키로 사용하시는 것은 어떨까요?
그외 추가적으로 리눅스 커널 드라이버 커뮤니티(또는 제작진) 측에 Caps Lock 키 및 Num Lock 의 동작을 변경하는 방법이 있는지 문의해보시는 방법이 있습니다.
