### ISSUE TITLE
Clone fails on Windows Git.

### ISSUE THREAD

**Issue by john-preston** [hamonikr/nimf#55]
After one of recent commits this repository is impossible to clone on Windows Git due to the filename problem:
```
error: invalid path 'manjaro-arm/nimf-1:1.2.0.r22.01ae33c-1-aarch64.pkg.tar.xz'
```
This repository is used as a submodule in Telegram Desktop and it would be great if I could clone it on all systems.

**Comment by bdh1993** [comment]
Hi, john-preston

I think it's a problem because the file name contains a lot of special characters.
The name was simply changed.

I tested it on the Windows and it worked well.

**Comment by john-preston** [comment]
Thanks!
