### ISSUE TITLE
21.10에서 설치 불가 (Unable to locate package)

### ISSUE THREAD

**Issue by maxswjeon** [hamonikr/nimf#56]
**버그 설명**
21.10에서 `Unable to locate package nimf` 에러 발생.

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
21.10에서 README.md에 나와있는 대로 설치를 진행하였을 때, `sudo apt install nimf nimf-libhangul` 실행시 다음 에러 발생.

**예상한 결과**
nimf 패키지를 찾아 인스톨 가능하여야 함.

**Screenshots**
![image](https://user-images.githubusercontent.com/10355032/151690810-2e82b268-ea58-4e5a-a643-7e5e8f325e82.png)

**자신의 PC 환경**
 - OS: Ubuntu 21.10
 - Browser 해당없음
 - Version 해당없음

**Comment by Mchito** [comment]
저도 apt로 했더니 안되서 어떻게 해야되나 싶었는데 release에 보시면 우분투 21.10 전용 .deb이 있어요. 
https://github.com/hamonikr/nimf/releases

**Comment by Mchito** [comment]
저도 어떻게 설치하나 싶었는데 release에 우분투 21.10에 전용  .deb 패키지가 있습니다.
https://github.com/hamonikr/nimf/releases
.deb 파일 전부 다운로드 하시고 한 디렉토리에 모아주세요. 그리고 터미널에
sudo dpkg -i *.deb

**Comment by whale124** [comment]
감사합니다. 덕분에 해결했습니다.
추가로 모든 파일 다 설치하면 중국어, 일본어 등 불필요한 언어도 설치됩니다. 아래 4개 패키지만 설치해도 될꺼 같네요.
(제 컴퓨터에 아래 4개 패키지만 깔려있었습니다.)

https://github.com/hamonikr/nimf/releases/download/1.3.0hamonikr40.7/nimf_1.3.0hamonikr40.7_amd64.deb
https://github.com/hamonikr/nimf/releases/download/1.3.0hamonikr40.7/nimf-libhangul_1.3.0hamonikr40.7_amd64.deb
https://github.com/hamonikr/nimf/releases/download/1.3.0hamonikr40.7/libnimf1_1.3.0hamonikr40.7_amd64.deb
https://github.com/hamonikr/nimf/releases/download/1.3.0hamonikr40.7/qtbase-abi-5-9-5-dummy_1.3.0hamonikr40.7_amd64.deb
