### ISSUE TITLE
22.04 complains about the deprecated key storage when PPA is used.

### ISSUE THREAD

**Issue by mxa** [hamonikr/nimf#60]
Message;
`https://pkg.hamonikr.org/dists/focal/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.`

**Comment by mxa** [comment]
The user can somehow convert the key to ne new gpg file however:
https://askubuntu.com/questions/1398344/apt-key-deprecation-warning-when-updating-system

**Comment by bdh1993** [comment]
Hi mxa

please add the repository again
fixed it.

The trust gpg was created and added to the trusted.gpg.d folder.

```
curl -sL https://pkg.hamonikr.org/add-hamonikr.apt | sudo -E bash -
```
