### ISSUE TITLE
중국어 입력 작동 안 함 Chinese input not working

### ISSUE THREAD

**Issue by sepiabrown** [hamonikr/nimf#61]
**버그 설명**
`Chinese(rime)`을 선택해도 중국어 입력이 안됩니다.
베트남어의 `han`을 선택하고 'ha'를 치면 1.呵 2.哈 3.訶 4.诃 이런식으로 글자가 뜨는데 중국어 Chinese(rime)을 선택했을 때도 비슷하게 영어를 치면 중국어가 떠야되는데 그러지 않습니다. 아이콘 모양도 설정에서 simplified chinese를 설정하면 간자체 모양 아이콘(汉)이 떠야되는데 그러지 않고 번자체 모양 (漢)이 뜹니다.

Chinese input while choosing `Chinese(rime)` is not working.
If you choose `han` under `Vietnamese` and input 'ha', words like 1.呵 2.哈 3.訶 4.诃 pop up. Similar effect should happen when choosing `Chinese(rime)` and typing some English letters but it doesn't work. Indicator Icon also shows traditional chinese mode(漢) even though `simplifed chinese` mode  in the setting is chosen. Correct behavior should be the icon showing 汉.

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. Click on the indicator icon
2. Choose `Chinese(rime)`
3. Type 'hao'

**예상한 결과**
Words like 好 should appear underneath 'hao'

**Screenshots**
현상이 발생해야하는데 아무런 현상이 발생하지 않아 screenshot이 없음.

**자신의 PC 환경**
 - OS: Ubuntu 22.04 in VirtualBox
 - Tested inside terminal

**Comment by chaeya** [comment]
우분투 환경은 아니고 조금 전 테스트 한 환경은 하모니카 5.0과 리눅스민트 20.3 입니다.
아래의 과정으로 테스트 했습니다.

1) 먼저 중국어 언어 패키지를 설치
![celluloid-shot0003](https://user-images.githubusercontent.com/405502/195338489-cd123047-2c5c-4314-a446-cf1bac3dcca8.jpg)
합니다. 

2) 님프를 설치하고 추가 언어를 설치합니다.
![celluloid-shot0004](https://user-images.githubusercontent.com/405502/195338515-571cfb97-438b-45d9-afaa-7aa1677ffd34.jpg)

3) 중국어 키보드로 전환하여 테스트 합니다.

![celluloid-shot0008](https://user-images.githubusercontent.com/405502/195338399-1208df6b-8b3a-41db-9077-c214e11128a6.jpg)


지금 테스트한 환경에서는 정상적으로 입력이 되고 있습니다.

**Comment by sepiabrown** [comment]
문제의 원인은 `nimf-rime`을 처음 깔고 다시 재부팅 했을 때 `~/.config/nimf/rime/luna_pinyin.userdb` 폴더 및 내부 파일들이 바로 생성되지 않아서 인 듯 합니다. 다시 껐다 키니까 위의 폴더 및 내부 폴더가 잘 생성되었고 중국어 입력이 정상적으로 작동하는 것을 우분투와 하모니카os 모두에서 확인했습니다.

The cause of the problem seems to be that when `nimf-rime` is installed for the first time and rebooted, the folder `~/.config/nimf/rime/luna_pinyin.userdb` and its files are not created. After rebooting again the folder and its files are created and chinese input work as expected. Tested both in ubuntu and hamonikr OS.

**Comment by hodong-kim** [comment]
> 문제의 원인은 `nimf-rime`을 처음 깔고 다시 재부팅 했을 때 `~/.config/nimf/rime/luna_pinyin.userdb` 폴더 및 내부 파일들이 바로 생성되지 않아서 인 듯 합니다. 다시 껐다 키니까 위의 폴더 및 내부 폴더가 잘 생성되었고 중국어 입력이 정상적으로 작동하는 것을 우분투와 하모니카os 모두에서 확인했습니다.
> 
> The cause of the problem seems to be that when `nimf-rime` is installed for the first time and rebooted, the folder `~/.config/nimf/rime/luna_pinyin.userdb` and its files are not created. After rebooting again the folder and its files are created and chinese input work as expected. Tested both in ubuntu and hamonikr OS.

그 문제는 전에 확인해봤는데 rime 버그입니다.
