### ISSUE TITLE
LMDE 5 Elsie 에서 nimf 설치가 안 되는 문제

### ISSUE THREAD

**Issue by tmin1986** [hamonikr/nimf#63]
OS: Linux Mint Debian Edition 5 "Elsie"

https://update.hamonikr.org 저장소를 추가하고 nimf를 설치하려고 하면 

-----------------------------------------

The following packages have unmet dependencies:
 nimf : Depends: qtbase-abi-5-12-8 but it is not installable
E: Unable to correct problems, you have held broken packages.

-----------------------------------------

라는 에러 메시지가 나면서 설치가 불가능한 상황이 계속됩니다.

저장소를 살펴보면 사실 이미 설치되어 있는 qtcore 패키지들로 설치 조건 자체는 충족되는 것 같은데 레거시 디펜던시 문제로 기존에는 qtbase-abi-5-9-5-dummy 더미 패키지를 제공해서 해결해왔던 것이. qtcore의 버전이 올라가면서 기존 더미 패키지로는 디펜던시가 맞지 않는 상황이 발생한 것 같습니다. 문제를 어떻게 해결하는 것이 가장 좋을까요?

분명히 올 여름까지 별 문제 없이 잘 설치되던 것이 갑자기 시스템 재설치 후 설치가 안 되어서 당황했네요.

**Comment by chaeya** [comment]
알려주신 Linux Mint Debian Edition 5 "Elsie" 환경에서 새로 빌드해서 배포했습니다. 

아래와 같이 설치해보시기 바랍니다.

```
sudo rm -f /etc/apt/sources.list.d/hamonikr*.list
curl -sL https://pkg.hamonikr.org/add-hamonikr.apt | sudo -E bash -
sudo apt install nimf nimf-libhangul
```

**Comment by tmin1986** [comment]
해결되었습니다. 감사합니다.
