### ISSUE TITLE
make appimage format , it run every

### ISSUE THREAD

**Issue by qq895311511** [hamonikr/nimf#67]
**버그 설명**
어떤 버그인지 내용을 적어주세요

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.

**예상한 결과**
이 기능을 동작시킬때 예상한 결과를 적어주세요.

**Screenshots**
가능하다면 화면 캡처를 포함해주세요. (이미지를 드래그앤드롭으로 업로드하세요)

**자신의 PC 환경**

**Comment by hodong-kim** [comment]
nimf 입력기에는 gtk 입력 모듈, qt 입력 모듈 등을 포함하고 있는데,  gtk 입력 모듈 및 qt 입력 모듈은 각각 특정 gtk 디렉토리, qt 디렉토리에 설치되어야 합니다.  AppImage 로는 그것을 할 수가 없습니다.
