### ISSUE TITLE
Wayland에서 특정 애플리케이션에서 한국어 입력 불가

### ISSUE THREAD

**Issue by GiftShower** [hamonikr/nimf#69]
**버그 설명**
Wayland 환경에서 kitty나 Steam과 같은 특정 프로그램에서 한국어를 입력할 수 없습니다.

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. Wayland 환경에서 nimf 입력기를 통해 스팀과 같은 프로그램에서 한국어 입력
2. 한국어가 아닌 영어가 입력됨.

**예상한 결과**
한국어가 정상적으로 입력되어야 함.

**자신의 PC 환경**
 - OS: Arch Linux, Wayland (Hyprland)

**Comment by hodong-kim** [comment]
wayland 및 kitty, stream 의 버그입니다.

wayland 의 입력 버그에 대해서는 아래 문서를 읽어보시면 되겠습니다.

(한국어 버전) https://nimfsoft.art/ko/blog/2022/09/09/the-reality-of-wayland-input-methods-in-2022/
