### ISSUE TITLE
flatpak 으로 설치한 slack 앱 (electronjs 로 구현된 것으로 보임)에서 nimf 로 한글 입력 불가.

### ISSUE THREAD

**Issue by eubnara** [hamonikr/nimf#70]
**버그 설명**

flatpak 으로 설치한 (snap store 에서 받은 것도 현상은 동일합니다.) slack 앱에서 한글 입력이 불가능합니다.
이 앱은 electronjs 로 구현된 것으로 보이며 https://github.com/flathub/com.slack.Slack/issues/21#issuecomment-437234774 여기서 설명하고 있는 workaround 방법으로 다음 명령어로 실행하면 한글입력이 됩니다.

```
flatpak run --env=GTK_IM_MODULE=xim com.slack.Slack
```
그런데 GTK_IM_MODULE 을 nimf 로 하면 동작하지 않습니다.

**버그 재현 과정**

1. slack 앱을 설치
2. 한글 입력을 시도
3. 한글 전환이 안됨.

**예상한 결과**
한글 입력 성공

**Screenshots**
가능하다면 화면 캡처를 포함해주세요. (이미지를 드래그앤드롭으로 업로드하세요)

**자신의 PC 환경**
 - OS: KDE Neon
```
❯ uname -a
Linux eub-21ckcto1ww 6.2.0-36-generic #37~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Mon Oct  9 15:34:04 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

~ 
❯ lsb_release -a
No LSB modules are available.
Distributor ID:	Neon
Description:	KDE neon 5.27
Release:	22.04
Codename:	jammy
```

 - Browser: firefox
 - Version:

**Comment by hodong-kim** [comment]
flatpak, snap, gtk, qt 등의 버그입니다. 통합 API가 없어서 발생하는 문제입니다.

아래와 같은 통합 API 를 설계하여 이를 flatpak, snap, gtk, qt 등에서 채택하여야 해결됩니다. wayland 입력 문제도 마찬가지입니다.

https://nimfsoft.art/ko/cim/

flatpak, snap, gtk, qt, wayland 측에 통합 API 를 설계하여 이를 채택하고 보급하라고 끊임없이 문제를 제기해야 해결될 가능성이 있으리라 봅니다.
