### ISSUE TITLE
데비안 ARM64에서 님프 설정 창이 빈 화면으로 나옵니다.

### ISSUE THREAD

**Issue by hansm629** [hamonikr/nimf#72]
**버그 설명**
Termux PRoot-Distro Debian ARM64 리눅스에 라즈베리파이 저장소 repo를 추가해서
님프를 설치했는데 님프 설정 창을 실행해도 설정창이 빈 화면으로 나옵니다.

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. curl -sL https://pkg.hamonikr.org/add-hamonikr-arm64.apt | sudo -E bash -
2. sudo apt update 
3. wget https://pkg.hamonikr.org/pool/main/q/qtbase-abi-5-12-8/qtbase-abi-5-12-8_1.0_all.deb
4. sudo dpkg -i qtbase-abi-5-12-8_1.0_all.deb
5. sudo apt install nimf nimf-libhangul
6. im-config -n nimf
7. 님프 설정 창이 실행되지 않아서 "프로그램->기타->님프 설정" 으로 수동 실행
8. 님프 설정 창이 실행되었지만 빈 화면으로 표시됨

**예상한 결과**
님프 설정 창에 설정 구성들이 정상적으로 표시되어야함

**Screenshots**
![스크린샷_2023-12-20_22-06-35](https://github.com/hamonikr/nimf/assets/101167173/cc05291e-144e-4600-bfc5-cd582b6eadfa)

**자신의 PC 환경**
 - OS: Debian GNU/Linux trixie/sid aarch64
 - Host: samsung SM-S918N 
 - DE: Xfce 4.18 
 - Browser : chromium

혹시 데비안 리눅스 환경에
라즈베리파이 repo로 설치해서 발생한 문제이려나요?

해당 증상 해결 방법과
우분투 ARM64나 데비안 ARM64 저장소가 추후 추가될 가능성이 있는지 문의드립니다.

**Comment by chaeya** [comment]
최근에 arm64 저장소를 업데이트했습니다. 아래 링크한 문서를 참고하시기 바랍니다.
https://hamonikr.org/board_project/130447

**Comment by hansm629** [comment]
> 최근에 arm64 저장소를 업데이트했습니다. 아래 링크한 문서를 참고하시기 바랍니다. https://hamonikr.org/board_project/130447

@chaeya 

감사합니다! 해결되었습니다!

갤럭시탭S9 울트라에 설치한 Termux PRoot-Distro Debian trixie/sid aarch64로 테스트했습니다.

모두 잘 작동하네요!
제일 큰 차이가 한영키로 한글 입력이 전환되는게 감동입니다 ㅠㅠ

기존 fcitx와 ibus의 경우 한영키로 설정 시 안드로이드 시스템의 한영키와 충돌해서 한영키로 한글 전환 불가했는데
님프는 전혀 문제없네요!

역시 소문대로 최고의 한글입력기입니다!

![스크린샷_2024-01-01_04-39-36](https://github.com/hamonikr/nimf/assets/101167173/dec22000-e83d-4c70-9e12-92f1e81e8604)
