### ISSUE TITLE
Cannot install nimf on Debian 12 Bookworm

### ISSUE THREAD

**Issue by RoonMoonlight** [hamonikr/nimf#73]
**Describe the bug**
[I followed instruction as written on README](https://github.com/hamonikr/nimf#install), but nimf refuses to be installed on Debian 12 due to unmet dependencies.

**To Reproduce**
Steps to reproduce the behavior, please provide code snippets or a repository:
1. Follow the instructions as written on README on Debian 12 Bookworm.
2. `The following packages have unmet dependencies` error occurs and cannot install the package.

```
~$ sudo apt install nimf nimf-libhangul
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 nimf : Depends: qtbase-abi-5-15-6 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Expected behavior**
It should be able to install the package without any issues.

**Screenshots**
None.

**Your PC environment**
 - OS: Debian 12 Bookworm (SpiralLinux 12)

**Comment by chaeya** [comment]
I updated the APT repository addition script for Debian a little while ago. 
Now, nimf will be installed normally in Debian bookworm using the method below.

```
# Add nimf  Repo
wget -qO- https://update.hamonikr.org/add-update-repo.apt | sudo -E bash -

# install nimf 
sudo apt install nimf nimf-libhangul
```
