### ISSUE TITLE
Android - Termux -proot-distro ubunu에 repo가 추가되지 않는 문제

### ISSUE THREAD

**Issue by yanghoeg** [hamonikr/nimf#77]
안녕하세요
우선 좋은 오픈소스 제공해주셔서 감사합니다.
안드로이드 어플리케이션중 Termux라는 프로그램이 있습니다. 여기에 proot-distro로 ubuntu를 설치할 수 있습니다.

한글입력기-nimf를 사용하기 위해 repo를 추가하기  위해 다음의 명령어를 입력했으나 /etc/apt/source.list.d에 repo가 생성되지 않았습니다.
`wget -qO- https://update.hamonikr.org/add-update-repo.apt | sudo -E bash - `

이유를 확인해보니 위주소 repo ${codename}에 noble이 포함되어 있지 않아서 repo가 추가되지 않은것 같습니다.
![source list](https://github.com/hamonikr/nimf/assets/134801173/c645b433-8cd2-4705-989a-fae87efb0f96)

![image](https://github.com/hamonikr/nimf/assets/134801173/e5875c97-e88f-4f64-87f8-b56f5a75919c)
따라서 마지막 분기문으로
`        elif [[ "X${CODENAME}" == "Xnoble" ]]
            echo "deb [arch=arm64] http://pkg.hamonikr.org/ bionic main" > /etc/apt/sources.list.d/hamonikr.list
            echo "#deb-src [arch=arm64] http://pkg.hamonikr.org/ bionic main" >> > /etc/apt/sources.list.d/hamonikr.list
        fi`
위를 추가하니 설치는 되었습니다.
bionic을 써도 되는지는 모르겠지만 위 코드나 유사한 코드 추가를 요청드립니다

그럼 좋은하루되세요
감사합니다

**Comment by chaeya** [comment]
요청하신 코드는 추가했습니다. 
이 패키지는 현재 ubuntu 24.04 noble arm64 버전에서 빌드된 패키지가 아니기 때문에 
혹시 구동에 문제가 있는 경우 이슈 리포팅을 해주시면 감사하겠습니다.

**Comment by yanghoeg** [comment]
> 요청하신 코드는 추가했습니다. 이 패키지는 현재 ubuntu 24.04 noble arm64 버전에서 빌드된 패키지가 아니기 때문에 혹시 구동에 문제가 있는 경우 이슈 리포팅을 해주시면 감사하겠습니다.

 안녕하십니까 제가 코드를 좀 잘못썼습니다. 죄송합니다
'        elif [ "X${CODENAME}" == "Xnoble" ]; then
            echo "deb [arch=arm64] http://pkg.hamonikr.org/ bionic main" > /etc/apt/sources.list.d/hamonikr.list
            echo "#deb-src [arch=arm64] http://pkg.hamonikr.org/ bionic main" >>/etc/apt/sources.list.d/hamonikr.list
        fi
'
위로 수정 부탁드리겠습니다

**Comment by chaeya** [comment]
수정사항 반영했습니다. 업데이트 후 확인해보세요

**Comment by yanghoeg** [comment]
> 수정사항 반영했습니다. 업데이트 후 확인해보세요
![image](https://github.com/hamonikr/nimf/assets/134801173/65a7d7fd-0f21-42d8-b586-69ea39818edb)

![image](https://github.com/hamonikr/nimf/assets/134801173/ed62a6a6-35f1-4df7-9bed-e8ca624c4729)

넵 덕분에 설치 잘했습니다 감사합니다!
