### ISSUE TITLE
한국어 입력 방법에 아무 자판도 나오지 않음

### ISSUE THREAD

**Issue by uaevuon** [hamonikr/nimf#79]
**버그 설명**
한국어에 아무 입력 방법이 나오지 않음

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.
1. readme에 따라 fedora 40 환경에서 nimf 설치
2. 터미널에 nimf-settings
3. 한국어(libhangul) 선택
4. 입력 방법에 아무 자판도 뜨지 않고 터미널에서 아래 오류가 나옴

(nimf-settings:5202): GModule-CRITICAL **: 15:21:46.669: g_module_symbol: assertion 'module != NULL' failed

(nimf-settings:5202): nimf-WARNING **: 15:21:46.672: nimf-settings.c:510: (null)

(nimf-settings:5202): GModule-CRITICAL **: 15:21:46.672: g_module_close: assertion 'module != NULL' failed

**예상한 결과**
입력 방법에 자판 나열됨

**Screenshots**
가능하다면 화면 캡처를 포함해주세요. (이미지를 드래그앤드롭으로 업로드하세요)
![2024-07-23-15-22-45](https://github.com/user-attachments/assets/4dd5677b-7a37-41aa-bfa2-125f31abf9fc)

**자신의 PC 환경**
 - OS: fedora 40

**Comment by chaeya** [comment]
배포한 rpm 파일로 테스트해보니 fedora40에 포함된 libhangul 패키지가 
최신버전이 아니라서 생기는 오류 같습니다.

아래의 방법으로 libhangul 최신버전을 설치 후 시도해보시거나, srpm 에서 rpm를 생성해서 시도해보실 수 있습니다.

### 1) 빌드 의존성 패키지 설치
```
sudo dnf install anthy-devel gcc-c++ glib2-devel gtk-doc gtk2-devel gtk3-devel intltool libappindicator-gtk3-devel libhangul-devel librime-devel librsvg2-tools libtool libxkbcommon-devel libxklavier-devel m17n-db-devel m17n-lib-devel qt5-qtbase-devel qt5-qtbase-private-devel qt6-qtbase-devel qt6-qtbase-private-devel wayland-devel naver-nanum-fonts-all wayland-protocols-devel expat expat-devel libayatana-appindicator-gtk3-devel.x86_64 im-chooser
```

###  2) ibhangul 최신 버전 설치
```
git clone https://github.com/libhangul/libhangul.git \
 && cd libhangul \
 && ./autogen.sh \
 && ./configure --prefix=/usr \
 && make \
 && sudo make install
```

여기까지만 하고 설치한 nimf 를 실행해서 한국어에 다음과 같이 나오는지 확인해보시기 바랍니다.
![fedora40_nimf-settings](https://github.com/user-attachments/assets/8b1649a5-dd1e-4203-8fde-87e97c5d9afb)

만약 제대로 동작하지 않으면, 다음과 같이 직접 rpm 파일을 만들어서 설치해볼수 있습니다.

### 3) srpm 에서 rpm 빌드
```
# 설치한 패키지 제거
sudo dnf remove nimf-1.3.8-1.fc40.x86_64.rpm

# srpm 에서 rpm 생성
sudo dnf install rpm-build rpmdevtools
rpmdev-setuptree
cd ~/
wget https://github.com/hamonikr/nimf/releases/download/v1.3.8/nimf-1.3.8-1.fc40.src.rpm
rpm -ivh nimf-1.3.8-1.fc40.src.rpm
rpmbuild -ba rpmbuild/SPECS/nimf.spec

# 빌드한 rpm  설치
sudo rpm -ivh rpmbuild/RPMS/x86_64/nimf-1.3.8-1.fc40.x86_64.rpm 
```

그리고 아래 링크는 도커로 fedora 환경에서 프로젝트를 컴파일 하고 설치하는 과정을 테스트하고 있는 내용입니다.
https://github.com/hamonikr/nimf/blob/master/.docker/fedora.latest.Dockerfile
rpm 파일 설치가 문제가 있는 경우 이와 같은 순서로 소스코드를 컴파일해서 설치해볼 수 도 있습니다.

**Comment by uaevuon** [comment]
2번을 따라 libhangul 최신 버전을 빌드해 설치하니 해결되었습니다.
![2024-07-23-22-16-54](https://github.com/user-attachments/assets/2973f612-bb53-4e93-848f-73429619cfbe)
