### ISSUE TITLE
build 가이드 쪽의 armv7l 내용 추가 요청 드립니다.

### ISSUE THREAD

**Issue by davidjung-kr** [hamonikr/nimf#8]
안녕하세요 :smiley: 

오렌지파이라는 싱글보드 컴퓨터의  PC+([Orange Pi PC+](http://www.orangepi.org/orangepipcplus/)) 모델에서 nimf을 빌드/설치까지 해보았는데요.
build페이지에 추가하면 좋을 만한 내용 전달 드립니다.

# 빌드 환경
* OS: Armbian Bionic(kernel 5.3.y)
* Chipset: Allwinner H3
* Branch: 2020/01/01 02:00 기준 `master`

# 개선요청
## 빌드 패키지 추가
`debuild -S -uc -us` 하는 과정에서 아래 2개의 패키지에 대해 추가설치 필요 했습니다.
```
fakeroot
libgtk-3-bin
```

## 패키지 만든 후 작업내용 설명추가
`debuild -b -uc -us` 한 다음 설치와 세팅 방법을 추가하면 좋을 듯 합니다.

저는 아래와 같이 작업 했습니다.

```
// 패키지 설치
sudo apt-get install -y libglib2.0-dev intltool libgtk-3-dev libgtk2.0-dev libqt4-dev qtbase5-dev qtbase5-private-dev libappindicator3-dev librsvg2-bin libhangul-dev libanthy-dev anthy librime-dev libxkbcommon-dev libwayland-dev wayland-protocols libxklavier-dev libm17n-dev m17n-db gtk-doc-tools devscripts build-essential debhelper fakeroot libgtk-3-bin

git clone https://github.com/hamonikr/nimf.git

cd nimf

debuild -b -uc -us

// 바이너리 패키지 빌드 후 설치
cd ..
sudo dpkg -i ./libnimf1_2019.08.14-0~201908141206~hamonikr14.1_armhf.deb
sudo dpkg -i ./nimf_2019.08.14-0~201908141206~hamonikr14.1_armhf.deb
sudo dpkg -i ./nimf-libhangul_2019.08.14-0~201908141206~hamonikr14.1_armhf.deb

// 입력기를 nimf로 변경
im-config -n nimf

// 재부팅
reboot
```

_**주의:**_ _패키지 받고 빌드까지 40분 이상 걸립니다._

현재 이 글도 오렌지파이 PC+에 nimf로 작성하고 있습니다. :smile:
라즈베리파이 같은 ARM 환경 사용자 분들에게 도움이 되셨으면 좋겠네요.

**Comment by chaeya** [comment]
@LukeHan1128 위키문서에 위의 내용을 추가해서 반영해주시면 좋겠네요.

**Comment by LukeHan1128** [comment]
@davidjung-kr 
전달해 주신 내용을 wiki에 등록 하였습니다.
확인해 보시고 댓글 달아주시면 이상 없는 경우 해당 이슈를 종료하겠습니다.

**Comment by chaeya** [comment]
@davidjung-kr 위키 페이지에 해당내용을 추가하여 반영했습니다. 기여해 주셔서 감사합니다

**Comment by davidjung-kr** [comment]
안녕하세요.
뒤늦게 반영 해주신 내용 확인했습니다. 위키에 내용 등재해주셔서 감사합니다. :smile: 

저가형 싱글보드에 들어가는 프로세서 중 Allwinner H3 프로세서가 그나마 가장 안정화 되어 있고 많이 쓰이는 편인데, 이번주 중으로 제가 빌드한 `*.deb` 패키지도 이곳에 업로드 하겠습니다.
**Armbian 우분투커널 + H3 프로세서** 환경이라면 문제 없이 설치 가능할 듯 하네요.

감사합니다.

**Comment by davidjung-kr** [comment]
DEB 패키지 레포 추가하였습니다. : https://github.com/davidjung-kr/nimf-bin-armhf

**Comment by chaeya** [comment]
@davidjung-kr 님프를 위해서 기여해주셔서 감사합니다.
보내주신 내용은 아래 링크에 업데이트 했습니다.

https://github.com/hamonikr/nimf/wiki/Armbian-build

즐거운 하루 보내세요~
