### ISSUE TITLE
오픈수세에서 빌드 중 에러발생

### ISSUE THREAD

**Issue by TopSonicK** [hamonikr/nimf#80]
OS : openSUSE Leap 15.5

데스크탑 환경 : KDE Plasma Version 5.27.9

컴파일러 : Clang 15.0.7

설치한 의존성 패키지 : glib2-devel libtool gtk-doc intltool libhangul-devel libxkbcommon-devel gtk3-devel gtk2-devel rsvg-convert wayland-protocols-devel libayatana-appindicator3-devel libxklavier-devel

설치에 사용한 소스 : 하모니카 공식 소스

설치 진행 

1. 소스 내려받음 (git clone --recurse-submodules https://github.com/hamonikr/nimf)
2. 소스 폴더 이동 (cd nimf)
3. 의존성 패키지 설치 (sudo zypper in glib2-devel libtool gtk-doc intltool libhangul-devel libxkbcommon-devel gtk3-devel gtk2-devel rsvg-convert wayland-protocols-devel libayatana-appindicator3-devel libxklavier-devel)
4. 환경 설정 (./autogen.sh --disable-nimf-anthy --disable-nimf-m17n --disable-nimf-rime CXX=clang)
5. make (make -j $(nproc))

make 중간 오류 발생으로 빌드 제대로 되지 않음

![다운로드](https://github.com/user-attachments/assets/3edefbac-98cc-46cf-985f-12a2b80fe0cf)

nimf-libhangul 부분 빌드하다가 에러 나는 것 같은데 혹시 어떻게 해결하면 될까요?

**Comment by chaeya** [comment]
아래 환경에서 빌드 후 패키지를 새로 했습니다.
* opensuse-leap 15.6 
* Plasma 5.27.11

![os_info](https://github.com/user-attachments/assets/2e9f8eb7-ab6b-4542-982b-703066bff334)

wayland 와 x11 환경에서 테스트 되었습니다.

아래와 같이 설치해보세요.
```
wget https://github.com/hamonikr/nimf/releases/download/v1.3.8/nimf-1.3.8-2.opensuse_leap.x86_64.rpm

sudo rpm -ivh ./nimf-1.3.8-2.opensuse_leap.x86_64.rpm 
```
### 소스코드 컴파일 및 빌드
소스코드로 직접 컴파일하는 경우 아래와 같이 진행하세요.
```
# 의존패키지 설치
sudo zypper install rpm-build rpmdevtools anthy anthy-devel libexpat-devel \
    gcc-c++ glib2-devel gtk-doc gtk2-devel gtk3-devel intltool libhangul-devel \
    libtool libxkbcommon-devel libxklavier-devel wayland-devel wayland-protocols-devel \
    google-noto-sans-cjk-fonts libappindicator3-devel libayatana-appindicator3-devel librsvg-devel \
    libqt5-qtbase-devel libqt5-qtbase-private-headers-devel \
    qt6-base-devel qt6-base-private-devel rsvg-convert librime-devel m17n-lib-devel 


# 컴파일 및 설치
git clone --recurse-submodules https://github.com/hamonikr/nimf

cd nimf

./autogen.sh
./configure --prefix=/usr/local
make -j $(nproc)
sudo make install

# 환경변수 설정
echo -e "\nexport GTK_IM_MODULE=nimf\nexport QT4_IM_MODULE=xim\nexport QT_IM_MODULE=nimf\nexport XMODIFIERS=@im=nimf" >> ~/.bashrc \
 && echo -e "\nexport GTK_IM_MODULE=nimf\nexport QT4_IM_MODULE=xim\nexport QT_IM_MODULE=nimf\nexport XMODIFIERS=@im=nimf" >> ~/.zshrc

```
시스템 재시작후 테스트

**Comment by TopSonicK** [comment]
먼저 조언 감사드립니다. 컴파일러를 gcc로 바꿔서 다시 빌드해보겠습니다.

궁금한 점이 anthy, rime, m17n은 미사용인데 해당 의존패키지(anthy, anthy-devel, librime-devel, m17n-lib-devel) 도 설치를 해야합니까? 제가 설치한 의존성 패키지는 autogen.sh 출력결과 보고 필요한 패키지를 그때마다 찾아서 설치했는데 해당 패키지들이 반드시 필요한 패키지 인건지 궁금합니다.

**Comment by chaeya** [comment]
@TopSonicK 한국어만 사용하는 환경이라면 다른 패키지는 설치하지 않아도 됩니다. 

컴파일시 아래와 같이 설정하시면 다른 언어 지원 기능이 비활성화 됩니다.
```
git clone --recurse-submodules https://github.com/hamonikr/nimf
cd nimf

./autogen.sh
./configure --prefix=/usr/local --disable-nimf-anthy --disable-nimf-m17n --disable-nimf-rime
make -j $(nproc)
sudo make install

# 환경변수 설정
echo -e "\nexport GTK_IM_MODULE=nimf\nexport QT4_IM_MODULE=xim\nexport QT_IM_MODULE=nimf\nexport XMODIFIERS=@im=nimf" >> ~/.bashrc \
 && echo -e "\nexport GTK_IM_MODULE=nimf\nexport QT4_IM_MODULE=xim\nexport QT_IM_MODULE=nimf\nexport XMODIFIERS=@im=nimf" >> ~/.zshrc

```

**Comment by chaeya** [comment]
@TopSonicK 한국어만 설치되는 rpm 패키지를 아래에서 다운로드 받으실 수 있습니다.
```
wget https://github.com/hamonikr/nimf/releases/download/v1.3.8/nimf-1.3.8-2.opensuse_leap.kr.x86_64.rpm
sudo rpm -ivh ./nimf-1.3.8-2.opensuse_leap.kr.x86_64.rpm
```

**Comment by TopSonicK** [comment]
15.5에서 gcc-c++로 빌드 해도 이슈 해결 안됨.

opensuse 15.6으로 판올림 후 빌드시 해당 문제 해결, QT5/6에 대한 의존패키지 없어서 libqt5-qtbase-devel libqt5-qtbase-private-headers-devel qt6-base-devel qt6-base-private-devel 패키지 추가 설치 후 정상 빌드 확인.

올려주신 nimf-1.3.8-2.opensuse_leap.kr.x86_64.rpm은 m17n 의존성이 그대로 남아있었습니다.

도움 주셔서 감사합니다.
