### ISSUE TITLE
OpenSuse 15.6 Leap - GTK 앱에서 한글 사용 불가

### ISSUE THREAD

**Issue by TopSonicK** [hamonikr/nimf#82]
**버그 설명**
어떤 버그인지 내용을 적어주세요

파이어폭스 / 썬더버드 등 GTK 앱에서 한글 입력 불가

**버그 재현 과정**
어떤 과정으로 버그가 발생하는지 단계별로 과정을 설명해주세요.

1 ~/.bashrc 에 다음 내용 추가
export GTK_IM_MODULE=nimf

2 로그아웃 / 재부팅 후 GTK 앱 실행, 한글 입력 불가

3 시스템 언어 변경 후(한글 -> 영어) 로그아웃/재부팅, 한글 입력 불가

4 수동으로 nimf 입력을 한글(두벌식)로 변경, 인디케이터는 한글 입력 상태이나 GTK앱에서는 여전히 한글 입력 불가, QT에서는 정상적으로 입력

**예상한 결과**
이 기능을 동작시킬때 예상한 결과를 적어주세요.

**Screenshots**
가능하다면 화면 캡처를 포함해주세요. (이미지를 드래그앤드롭으로 업로드하세요)

**자신의 PC 환경**
 - OS: OpenSuse 15.6 Leap / KDE 5.115.0(X11)
 
 - Browser  : MozillaFirefox-branding-opensuse (ver 128.2.0ESR)
 - Thunderbird : 115.14.0

**Comment by chaeya** [comment]
아래 패키지를 이용해서 설치 후 테스트 결과,  파이어폭스에서 한글 입력이 문제없이 되고 있습니다.
https://github.com/hamonikr/nimf/releases/download/v1.3.8/nimf-1.3.8-2.opensuse_leap.x86_64.rpm

### 테스트 환경
운영 체제: openSUSE Leap 15.6
KDE Plasma 버전: 5.27.11
KDE 프레임워크 버전: 5.115.0
Qt 버전: 5.15.12
커널 버전: 6.4.0-150600.23.14-default(64비트)
그래픽 플랫폼: X11
프로세서: 12 × AMD Ryzen 5 5500U with Radeon Graphics
메모리: RAM 17.4 GiB
그래픽 프로세서: AMD Radeon Graphics
제조사: LENOVO
제품 이름: 82KT
시스템 버전: IdeaPad 3 14ALC6

### 환경변수 설정
cat .xprofile 
```
export $(/usr/lib/systemd/user-environment-generators/30-systemd-environment-d-generator)

GTK_IM_MODULE=nimf
QT4_IM_MODULE=xim
QT_IM_MODULE=nimf
XMODIFIERS=@im=nimf
```

### 파이어폭스 버전
![image](https://github.com/user-attachments/assets/c2d4e511-c97a-4bb6-b174-853a0b23bdbf)

### 썬더버드 버전
![image](https://github.com/user-attachments/assets/bd68a3ea-0e54-4420-b0fc-06bf49c9fbb8)

위 두개의 프로그램에서 한글입력을 확인했습니다.

테스트 환경에서는 문제가 재현되지 않는 상태이기 때문에, 이 환경과 차이점이 있는 부분을 추가로 확인해서 디버깅해야 할 것 같습니다.

**Comment by chaeya** [comment]
@TopSonicK virtualbox 로 새 OS를 깨끗하게 설치한 상태에서 다음과 같이 테스트했습니다.

처음 OS 설치는 한국어로 했습니다. 설치 후 다음의 과정으로 패키지를 설치했습니다.

 1) nimf 저장소에서 GPG 키 설치

```
# GPG 키 다운로드
wget https://github.com/hamonikr/nimf/raw/master/RPM-GPG-KEY-nimf

# GPG 키 설치
sudo rpm --import RPM-GPG-KEY-nimf

# 설치된 키 확인
rpm -qa gpg-pubkey --qf "%{NAME}-%{VERSION}-%{RELEASE}\n" | grep e42665b8
```

 2) 패키지 다운로드 및 설치

사용자는 한국어 패키지를 포함한 패키지 또는 다른 언어를 포함한 패키지를 선택하여 설치할 수 있습니다.

```
# 다른 언어를 사용할 경우
wget https://github.com/hamonikr/nimf/releases/download/v1.3.8/nimf-1.3.8-2.opensuse_leap.x86_64.rpm

sudo zypper install ./nimf-1.3.8-2.opensuse_leap.x86_64.rpm

# 한국어만 설치하고 싶은 경우
wget https://github.com/hamonikr/nimf/releases/download/v1.3.8/nimf-1.3.8-2.opensuse_leap.kr.x86_64.rpm

sudo zypper install ./nimf-1.3.8-2.opensuse_leap.kr.x86_64.rpm
```

 3) 재부팅

시스템을 재시작한 후 nimf를 사용.

## 스크린샷

화면과 같이 파이어폭스에서 한글 입력이 정상적으로 되고 있습니다.

![opensuse-nimf](https://github.com/user-attachments/assets/d6086d58-1411-4eec-9ea4-2775fe83fd11)


동일한 과정으로 테스트 해보신 후 여전히 문제가 있다면, 디버깅을 위해 추가적인 정보를 업데이트 해주시기 바랍니다.

**Comment by TopSonicK** [comment]
테스트 환경은 rpm 패키지를 이용해서 설치한게 아니라 --disable-nimf-anthy --disable-nimf-m17n --disable-nimf-rime CXX=clang으로 설정 한 후 소스코드 빌드 설치로 설치한 상태입니다. 환경변수를 .xprofile에 설정하지 않고 .bashrc에 설정한 상태 입니다.
저번 #80 이슈 에서 nimf-1.3.8-2.opensuse_leap.kr.x86_64.rpm 패키지에 m17n 의존성이 걸려 있어서 빌드 설치로 진행 했었습니다.
