### ISSUE TITLE
삭제하려면 어떻게해야할까요?

### ISSUE THREAD

**Issue by wiz9e** [hamonikr/nimf#88]
자유롭게 자신의 의견을 적어주세요.
페도라40 입니다.
도움 감사합니다.

**Comment by chaeya** [comment]
@wiz9e 패키지 관리도구를 사용해서 설치했다면 관리도구를 이용(`예 : sudo dnf remove nimf-x.x.x`)해서 삭제하고, 소스코드로 컴파일 후 설치한 경우라면 `sudo make uninstall` 로 삭제하면 될 것 같습니다.
